[
	" /usr/pgsql-9.5/bin:/data/root/perl5/bin:/usr/pgsql-9.5/bin:/data/root/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/data/root/.cabal/bin:/data/root/bin:/data/root/bin:/opt/chromium-browser",
	"ascii",
	"CP 54321",
	"CP 11111",
	"http://172.17.42.1:15678/",
	[],
	"",
	"CP 22222",
	"CP 37145",
	"CP 37146",
	"CP 34863",
	"http://172.17.42.1:15678/",
	"CP 34864",
	"http://172.17.42.1:15678/",
	"2016-06-15 13:11:22http%3A%2f%2ftieba.baidu.com%2f%3Fpage%3Ddiscovery.png",
	"Traceback (most recent call last):",
	"  File \"open.py\", line 198, in <module>",
	"    driver.find_element_by_link_text(\"æˆ‘\").click()",
	"  File \"/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py\", line 74, in click",
	"    self._execute(Command.CLICK_ELEMENT)",
	"  File \"/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py\", line 457, in _execute",
	"    return self._parent.execute(command, params)",
	"  File \"/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 233, in execute",
	"    self.error_handler.check_response(response)",
	"  File \"/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response",
	"    raise exception_class(message, screen, stacktrace)",
	"selenium.common.exceptions.WebDriverException: Message: unknown error: Element is not clickable at point (504, 67). Other element would receive the click: <img src=\"http://tb1.bdstatic.com/tb/%E9%A6%96%E9%A1%B5%E6%8B%A6%E6%88%AA%E5%9B%BE.png\" alt=\"\">",
	"  (Session info: chrome=38.0.2125.104)",
	"  (Driver info: chromedriver=2.10,platform=Linux 3.10.0-123.4.4.el7.x86_64 x86_64)",
	""
]
